version = 0.1

[default]
[default.global.parameters]
stack_name = "aws-lambda-form-processor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "aws-lambda-form-processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EmailRecipient=jon.laplante@jonlaplante.com EmailSender=noreply@example.com AllowedOrigins=https://productguyjon.info"
# parameter_overrides = "EmailRecipient=admin@example.com EmailSender=noreply@example.com AllowedOrigins=https://yourusername.github.io"
image_repositories = []
